"""
Senior QA Agent (Groq Llama-3.3-70b-versatile)
Reviews the SQL generated by the SQL Developer to ensure it is valid, secure, and uses real columns.
"""
import json
import logging
from groq import AsyncGroq
from app.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()

client = AsyncGroq(api_key=settings.groq_api_key)

QA_SYSTEM = """You are a Senior PostgreSQL Database Administrator.
Your job is to review a SQL query generated by a junior developer before it executes.
You will be given the Database Schema, the User's original question, and the Generated SQL.

Your review criteria:
1. Syntax errors: Is it valid PostgreSQL?
2. Schema validation: Do all tables and columns exist in the provided schema?
3. Security: Does it mutate data? (Reject DROP, DELETE, UPDATE, INSERT)

Respond strictly in JSON format with exactly:
{
  "is_valid": true|false,
  "reason": "Brief explanation of what is wrong (or 'looks good')",
  "fixed_sql": "The corrected raw SQL string if invalid. Null if valid."
}
Only output the JSON object, absolutely NO markdown code fences (no ```json).
"""

async def review_sql(schema_context: str, user_query: str, generated_sql: str) -> dict:
    prompt = f"### Schema\n{schema_context}\n\n### User Question\n{user_query}\n\n### Generated SQL\n{generated_sql}\n\nReview output in JSON:"
    
    try:
        completion = await client.chat.completions.create(
            model=settings.groq_qa_model,
            messages=[
                {"role": "system", "content": QA_SYSTEM},
                {"role": "user", "content": prompt}
            ],
            response_format={"type": "json_object"},
            temperature=0,
        )
        result_text = completion.choices[0].message.content.strip()
        result = json.loads(result_text)
        
        # Ensure fixed_sql is clean
        if result.get("fixed_sql"):
            clean = result["fixed_sql"].replace("```sql", "").replace("```", "").strip()
            result["fixed_sql"] = clean

        return result
    except Exception as e:
        logger.error(f"QAAgent review failed: {e}")
        # If QA fails, fallback to executing the original SQL
        return {"is_valid": True, "reason": f"QA check bypassed due to error: {e}", "fixed_sql": None}
